-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('MoveDTO_pb')


local VECTOR3 = protobuf.Descriptor();
local VECTOR3_X_FIELD = protobuf.FieldDescriptor();
local VECTOR3_Y_FIELD = protobuf.FieldDescriptor();
local VECTOR3_Z_FIELD = protobuf.FieldDescriptor();
local MOVEDTO = protobuf.Descriptor();
local MOVEDTO_ID_FIELD = protobuf.FieldDescriptor();
local MOVEDTO_POINT_FIELD = protobuf.FieldDescriptor();

VECTOR3_X_FIELD.name = "x"
VECTOR3_X_FIELD.full_name = ".msg.Vector3.x"
VECTOR3_X_FIELD.number = 1
VECTOR3_X_FIELD.index = 0
VECTOR3_X_FIELD.label = 2
VECTOR3_X_FIELD.has_default_value = false
VECTOR3_X_FIELD.default_value = 0.0
VECTOR3_X_FIELD.type = 1
VECTOR3_X_FIELD.cpp_type = 5

VECTOR3_Y_FIELD.name = "y"
VECTOR3_Y_FIELD.full_name = ".msg.Vector3.y"
VECTOR3_Y_FIELD.number = 2
VECTOR3_Y_FIELD.index = 1
VECTOR3_Y_FIELD.label = 2
VECTOR3_Y_FIELD.has_default_value = false
VECTOR3_Y_FIELD.default_value = 0.0
VECTOR3_Y_FIELD.type = 1
VECTOR3_Y_FIELD.cpp_type = 5

VECTOR3_Z_FIELD.name = "z"
VECTOR3_Z_FIELD.full_name = ".msg.Vector3.z"
VECTOR3_Z_FIELD.number = 3
VECTOR3_Z_FIELD.index = 2
VECTOR3_Z_FIELD.label = 2
VECTOR3_Z_FIELD.has_default_value = false
VECTOR3_Z_FIELD.default_value = 0.0
VECTOR3_Z_FIELD.type = 1
VECTOR3_Z_FIELD.cpp_type = 5

VECTOR3.name = "Vector3"
VECTOR3.full_name = ".msg.Vector3"
VECTOR3.nested_types = {}
VECTOR3.enum_types = {}
VECTOR3.fields = {VECTOR3_X_FIELD, VECTOR3_Y_FIELD, VECTOR3_Z_FIELD}
VECTOR3.is_extendable = false
VECTOR3.extensions = {}
MOVEDTO_ID_FIELD.name = "id"
MOVEDTO_ID_FIELD.full_name = ".msg.MoveDTO.id"
MOVEDTO_ID_FIELD.number = 1
MOVEDTO_ID_FIELD.index = 0
MOVEDTO_ID_FIELD.label = 2
MOVEDTO_ID_FIELD.has_default_value = false
MOVEDTO_ID_FIELD.default_value = 0
MOVEDTO_ID_FIELD.type = 5
MOVEDTO_ID_FIELD.cpp_type = 1

MOVEDTO_POINT_FIELD.name = "point"
MOVEDTO_POINT_FIELD.full_name = ".msg.MoveDTO.point"
MOVEDTO_POINT_FIELD.number = 2
MOVEDTO_POINT_FIELD.index = 1
MOVEDTO_POINT_FIELD.label = 2
MOVEDTO_POINT_FIELD.has_default_value = false
MOVEDTO_POINT_FIELD.default_value = nil
MOVEDTO_POINT_FIELD.message_type = VECTOR3
MOVEDTO_POINT_FIELD.type = 11
MOVEDTO_POINT_FIELD.cpp_type = 10

MOVEDTO.name = "MoveDTO"
MOVEDTO.full_name = ".msg.MoveDTO"
MOVEDTO.nested_types = {}
MOVEDTO.enum_types = {}
MOVEDTO.fields = {MOVEDTO_ID_FIELD, MOVEDTO_POINT_FIELD}
MOVEDTO.is_extendable = false
MOVEDTO.extensions = {}

MoveDTO = protobuf.Message(MOVEDTO)
Vector3 = protobuf.Message(VECTOR3)

