-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('Status_pb')


local STATUS = protobuf.Descriptor();
local STATUS_ID_FIELD = protobuf.FieldDescriptor();
local STATUS_DIRECT_FIELD = protobuf.FieldDescriptor();
local VECTOR2 = protobuf.Descriptor();
local VECTOR2_X_FIELD = protobuf.FieldDescriptor();
local VECTOR2_Y_FIELD = protobuf.FieldDescriptor();

STATUS_ID_FIELD.name = "id"
STATUS_ID_FIELD.full_name = ".msg.Status.id"
STATUS_ID_FIELD.number = 1
STATUS_ID_FIELD.index = 0
STATUS_ID_FIELD.label = 1
STATUS_ID_FIELD.has_default_value = false
STATUS_ID_FIELD.default_value = 0
STATUS_ID_FIELD.type = 5
STATUS_ID_FIELD.cpp_type = 1

STATUS_DIRECT_FIELD.name = "direct"
STATUS_DIRECT_FIELD.full_name = ".msg.Status.direct"
STATUS_DIRECT_FIELD.number = 2
STATUS_DIRECT_FIELD.index = 1
STATUS_DIRECT_FIELD.label = 1
STATUS_DIRECT_FIELD.has_default_value = false
STATUS_DIRECT_FIELD.default_value = nil
STATUS_DIRECT_FIELD.message_type = _VECTOR2
STATUS_DIRECT_FIELD.type = 11
STATUS_DIRECT_FIELD.cpp_type = 10

STATUS.name = "Status"
STATUS.full_name = ".msg.Status"
STATUS.nested_types = {}
STATUS.enum_types = {}
STATUS.fields = {STATUS_ID_FIELD, STATUS_DIRECT_FIELD}
STATUS.is_extendable = false
STATUS.extensions = {}
VECTOR2_X_FIELD.name = "x"
VECTOR2_X_FIELD.full_name = ".msg.Vector2.x"
VECTOR2_X_FIELD.number = 1
VECTOR2_X_FIELD.index = 0
VECTOR2_X_FIELD.label = 1
VECTOR2_X_FIELD.has_default_value = false
VECTOR2_X_FIELD.default_value = 0
VECTOR2_X_FIELD.type = 5
VECTOR2_X_FIELD.cpp_type = 1

VECTOR2_Y_FIELD.name = "y"
VECTOR2_Y_FIELD.full_name = ".msg.Vector2.y"
VECTOR2_Y_FIELD.number = 2
VECTOR2_Y_FIELD.index = 1
VECTOR2_Y_FIELD.label = 1
VECTOR2_Y_FIELD.has_default_value = false
VECTOR2_Y_FIELD.default_value = 0
VECTOR2_Y_FIELD.type = 5
VECTOR2_Y_FIELD.cpp_type = 1

VECTOR2.name = "Vector2"
VECTOR2.full_name = ".msg.Vector2"
VECTOR2.nested_types = {}
VECTOR2.enum_types = {}
VECTOR2.fields = {VECTOR2_X_FIELD, VECTOR2_Y_FIELD}
VECTOR2.is_extendable = false
VECTOR2.extensions = {}

Status = protobuf.Message(STATUS)
Vector2 = protobuf.Message(VECTOR2)

