-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('MoveDTO_pb')


local PLAYERDTO = protobuf.Descriptor();
local PLAYERDTO_ID_FIELD = protobuf.FieldDescriptor();
local PLAYERDTO_USERNAME_FIELD = protobuf.FieldDescriptor();
local MOVEDTO = protobuf.Descriptor();
local MOVEDTO_ID_FIELD = protobuf.FieldDescriptor();
local MOVEDTO_POINT_FIELD = protobuf.FieldDescriptor();
local MOVEDTO_STATUS_FIELD = protobuf.FieldDescriptor();
local VECTOR3 = protobuf.Descriptor();
local VECTOR3_X_FIELD = protobuf.FieldDescriptor();
local VECTOR3_Y_FIELD = protobuf.FieldDescriptor();
local VECTOR3_Z_FIELD = protobuf.FieldDescriptor();
local VECTOR2 = protobuf.Descriptor();
local VECTOR2_X_FIELD = protobuf.FieldDescriptor();
local VECTOR2_Y_FIELD = protobuf.FieldDescriptor();

PLAYERDTO_ID_FIELD.name = "id"
PLAYERDTO_ID_FIELD.full_name = ".msg.PlayerDTO.id"
PLAYERDTO_ID_FIELD.number = 1
PLAYERDTO_ID_FIELD.index = 0
PLAYERDTO_ID_FIELD.label = 1
PLAYERDTO_ID_FIELD.has_default_value = false
PLAYERDTO_ID_FIELD.default_value = 0
PLAYERDTO_ID_FIELD.type = 5
PLAYERDTO_ID_FIELD.cpp_type = 1

PLAYERDTO_USERNAME_FIELD.name = "UserName"
PLAYERDTO_USERNAME_FIELD.full_name = ".msg.PlayerDTO.UserName"
PLAYERDTO_USERNAME_FIELD.number = 2
PLAYERDTO_USERNAME_FIELD.index = 1
PLAYERDTO_USERNAME_FIELD.label = 1
PLAYERDTO_USERNAME_FIELD.has_default_value = false
PLAYERDTO_USERNAME_FIELD.default_value = ""
PLAYERDTO_USERNAME_FIELD.type = 9
PLAYERDTO_USERNAME_FIELD.cpp_type = 9

PLAYERDTO.name = "PlayerDTO"
PLAYERDTO.full_name = ".msg.PlayerDTO"
PLAYERDTO.nested_types = {}
PLAYERDTO.enum_types = {}
PLAYERDTO.fields = {PLAYERDTO_ID_FIELD, PLAYERDTO_USERNAME_FIELD}
PLAYERDTO.is_extendable = false
PLAYERDTO.extensions = {}
MOVEDTO_ID_FIELD.name = "id"
MOVEDTO_ID_FIELD.full_name = ".msg.MoveDTO.id"
MOVEDTO_ID_FIELD.number = 1
MOVEDTO_ID_FIELD.index = 0
MOVEDTO_ID_FIELD.label = 1
MOVEDTO_ID_FIELD.has_default_value = false
MOVEDTO_ID_FIELD.default_value = 0
MOVEDTO_ID_FIELD.type = 5
MOVEDTO_ID_FIELD.cpp_type = 1

MOVEDTO_POINT_FIELD.name = "point"
MOVEDTO_POINT_FIELD.full_name = ".msg.MoveDTO.point"
MOVEDTO_POINT_FIELD.number = 2
MOVEDTO_POINT_FIELD.index = 1
MOVEDTO_POINT_FIELD.label = 1
MOVEDTO_POINT_FIELD.has_default_value = false
MOVEDTO_POINT_FIELD.default_value = nil
MOVEDTO_POINT_FIELD.message_type = _VECTOR3
MOVEDTO_POINT_FIELD.type = 11
MOVEDTO_POINT_FIELD.cpp_type = 10

MOVEDTO_STATUS_FIELD.name = "status"
MOVEDTO_STATUS_FIELD.full_name = ".msg.MoveDTO.status"
MOVEDTO_STATUS_FIELD.number = 3
MOVEDTO_STATUS_FIELD.index = 2
MOVEDTO_STATUS_FIELD.label = 1
MOVEDTO_STATUS_FIELD.has_default_value = false
MOVEDTO_STATUS_FIELD.default_value = nil
MOVEDTO_STATUS_FIELD.message_type = _VECTOR2
MOVEDTO_STATUS_FIELD.type = 11
MOVEDTO_STATUS_FIELD.cpp_type = 10

MOVEDTO.name = "MoveDTO"
MOVEDTO.full_name = ".msg.MoveDTO"
MOVEDTO.nested_types = {}
MOVEDTO.enum_types = {}
MOVEDTO.fields = {MOVEDTO_ID_FIELD, MOVEDTO_POINT_FIELD, MOVEDTO_STATUS_FIELD}
MOVEDTO.is_extendable = false
MOVEDTO.extensions = {}
VECTOR3_X_FIELD.name = "x"
VECTOR3_X_FIELD.full_name = ".msg.Vector3.x"
VECTOR3_X_FIELD.number = 1
VECTOR3_X_FIELD.index = 0
VECTOR3_X_FIELD.label = 1
VECTOR3_X_FIELD.has_default_value = false
VECTOR3_X_FIELD.default_value = ""
VECTOR3_X_FIELD.type = 9
VECTOR3_X_FIELD.cpp_type = 9

VECTOR3_Y_FIELD.name = "y"
VECTOR3_Y_FIELD.full_name = ".msg.Vector3.y"
VECTOR3_Y_FIELD.number = 2
VECTOR3_Y_FIELD.index = 1
VECTOR3_Y_FIELD.label = 1
VECTOR3_Y_FIELD.has_default_value = false
VECTOR3_Y_FIELD.default_value = ""
VECTOR3_Y_FIELD.type = 9
VECTOR3_Y_FIELD.cpp_type = 9

VECTOR3_Z_FIELD.name = "z"
VECTOR3_Z_FIELD.full_name = ".msg.Vector3.z"
VECTOR3_Z_FIELD.number = 3
VECTOR3_Z_FIELD.index = 2
VECTOR3_Z_FIELD.label = 1
VECTOR3_Z_FIELD.has_default_value = false
VECTOR3_Z_FIELD.default_value = ""
VECTOR3_Z_FIELD.type = 9
VECTOR3_Z_FIELD.cpp_type = 9

VECTOR3.name = "Vector3"
VECTOR3.full_name = ".msg.Vector3"
VECTOR3.nested_types = {}
VECTOR3.enum_types = {}
VECTOR3.fields = {VECTOR3_X_FIELD, VECTOR3_Y_FIELD, VECTOR3_Z_FIELD}
VECTOR3.is_extendable = false
VECTOR3.extensions = {}
VECTOR2_X_FIELD.name = "x"
VECTOR2_X_FIELD.full_name = ".msg.Vector2.x"
VECTOR2_X_FIELD.number = 1
VECTOR2_X_FIELD.index = 0
VECTOR2_X_FIELD.label = 1
VECTOR2_X_FIELD.has_default_value = false
VECTOR2_X_FIELD.default_value = ""
VECTOR2_X_FIELD.type = 9
VECTOR2_X_FIELD.cpp_type = 9

VECTOR2_Y_FIELD.name = "y"
VECTOR2_Y_FIELD.full_name = ".msg.Vector2.y"
VECTOR2_Y_FIELD.number = 2
VECTOR2_Y_FIELD.index = 1
VECTOR2_Y_FIELD.label = 1
VECTOR2_Y_FIELD.has_default_value = false
VECTOR2_Y_FIELD.default_value = ""
VECTOR2_Y_FIELD.type = 9
VECTOR2_Y_FIELD.cpp_type = 9

VECTOR2.name = "Vector2"
VECTOR2.full_name = ".msg.Vector2"
VECTOR2.nested_types = {}
VECTOR2.enum_types = {}
VECTOR2.fields = {VECTOR2_X_FIELD, VECTOR2_Y_FIELD}
VECTOR2.is_extendable = false
VECTOR2.extensions = {}

MoveDTO = protobuf.Message(MOVEDTO)
PlayerDTO = protobuf.Message(PLAYERDTO)
Vector2 = protobuf.Message(VECTOR2)
Vector3 = protobuf.Message(VECTOR3)

