// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Cuser.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CUser struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CUser) Reset()         { *m = CUser{} }
func (m *CUser) String() string { return proto.CompactTextString(m) }
func (*CUser) ProtoMessage()    {}
func (*CUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5a3f361fccac9fd, []int{0}
}

func (m *CUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CUser.Unmarshal(m, b)
}
func (m *CUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CUser.Marshal(b, m, deterministic)
}
func (m *CUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CUser.Merge(m, src)
}
func (m *CUser) XXX_Size() int {
	return xxx_messageInfo_CUser.Size(m)
}
func (m *CUser) XXX_DiscardUnknown() {
	xxx_messageInfo_CUser.DiscardUnknown(m)
}

var xxx_messageInfo_CUser proto.InternalMessageInfo

func (m *CUser) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CUser) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CUser) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*CUser)(nil), "msg.CUser")
}

func init() { proto.RegisterFile("Cuser.proto", fileDescriptor_f5a3f361fccac9fd) }

var fileDescriptor_f5a3f361fccac9fd = []byte{
	// 106 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x76, 0x2e, 0x2d, 0x4e,
	0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0x2d, 0x4e, 0x57, 0xf2, 0xe7, 0x62,
	0x75, 0x0e, 0x2d, 0x4e, 0x2d, 0x12, 0xe2, 0xe3, 0x62, 0xca, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4,
	0x60, 0x0d, 0x62, 0xca, 0x4c, 0x11, 0x92, 0xe2, 0xe2, 0x00, 0xa9, 0xcd, 0x4b, 0xcc, 0x4d, 0x95,
	0x60, 0x52, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0xf3, 0x41, 0x72, 0x05, 0x89, 0xc5, 0xc5, 0xe5, 0xf9,
	0x45, 0x29, 0x12, 0xcc, 0x10, 0x39, 0x18, 0x3f, 0x89, 0x0d, 0x6c, 0xb8, 0x31, 0x20, 0x00, 0x00,
	0xff, 0xff, 0x99, 0x43, 0xa0, 0x2a, 0x6b, 0x00, 0x00, 0x00,
}
