// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Status.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Vector2 struct {
	X                    *int32   `protobuf:"varint,1,req,name=x" json:"x,omitempty"`
	Y                    *int32   `protobuf:"varint,2,req,name=y" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vector2) Reset()         { *m = Vector2{} }
func (m *Vector2) String() string { return proto.CompactTextString(m) }
func (*Vector2) ProtoMessage()    {}
func (*Vector2) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d276e6eb59dd817, []int{0}
}

func (m *Vector2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vector2.Unmarshal(m, b)
}
func (m *Vector2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vector2.Marshal(b, m, deterministic)
}
func (m *Vector2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vector2.Merge(m, src)
}
func (m *Vector2) XXX_Size() int {
	return xxx_messageInfo_Vector2.Size(m)
}
func (m *Vector2) XXX_DiscardUnknown() {
	xxx_messageInfo_Vector2.DiscardUnknown(m)
}

var xxx_messageInfo_Vector2 proto.InternalMessageInfo

func (m *Vector2) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *Vector2) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

type Status struct {
	Id                   *int32     `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Direct               []*Vector2 `protobuf:"bytes,2,rep,name=direct" json:"direct,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d276e6eb59dd817, []int{1}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Status) GetDirect() []*Vector2 {
	if m != nil {
		return m.Direct
	}
	return nil
}

func init() {
	proto.RegisterType((*Vector2)(nil), "msg.Vector2")
	proto.RegisterType((*Status)(nil), "msg.Status")
}

func init() { proto.RegisterFile("Status.proto", fileDescriptor_3d276e6eb59dd817) }

var fileDescriptor_3d276e6eb59dd817 = []byte{
	// 121 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x09, 0x2e, 0x49, 0x2c,
	0x29, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0x2d, 0x4e, 0x57, 0x52, 0xe5,
	0x62, 0x0f, 0x4b, 0x4d, 0x2e, 0xc9, 0x2f, 0x32, 0x12, 0xe2, 0xe1, 0x62, 0xac, 0x90, 0x60, 0x54,
	0x60, 0xd2, 0x60, 0x0d, 0x62, 0xac, 0x00, 0xf1, 0x2a, 0x25, 0x98, 0x20, 0xbc, 0x4a, 0x25, 0x3b,
	0x2e, 0x36, 0x88, 0x5e, 0x21, 0x3e, 0x2e, 0xa6, 0xcc, 0x14, 0xa8, 0x32, 0xa6, 0xcc, 0x14, 0x21,
	0x15, 0x2e, 0xb6, 0x94, 0xcc, 0xa2, 0xd4, 0xe4, 0x12, 0x09, 0x26, 0x05, 0x66, 0x0d, 0x6e, 0x23,
	0x1e, 0xbd, 0xdc, 0xe2, 0x74, 0x3d, 0xa8, 0x99, 0x41, 0x50, 0x39, 0x40, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xfb, 0x03, 0x4e, 0xd0, 0x7a, 0x00, 0x00, 0x00,
}
