// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CUser struct {
	Email                *string  `protobuf:"bytes,1,req,name=email" json:"email,omitempty"`
	Password             *string  `protobuf:"bytes,2,req,name=password" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CUser) Reset()         { *m = CUser{} }
func (m *CUser) String() string { return proto.CompactTextString(m) }
func (*CUser) ProtoMessage()    {}
func (*CUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_1874ca57eb0416de, []int{0}
}
func (m *CUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CUser.Unmarshal(m, b)
}
func (m *CUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CUser.Marshal(b, m, deterministic)
}
func (dst *CUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CUser.Merge(dst, src)
}
func (m *CUser) XXX_Size() int {
	return xxx_messageInfo_CUser.Size(m)
}
func (m *CUser) XXX_DiscardUnknown() {
	xxx_messageInfo_CUser.DiscardUnknown(m)
}

var xxx_messageInfo_CUser proto.InternalMessageInfo

func (m *CUser) GetEmail() string {
	if m != nil && m.Email != nil {
		return *m.Email
	}
	return ""
}

func (m *CUser) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*CUser)(nil), "msg.CUser")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_user_1874ca57eb0416de) }

var fileDescriptor_user_1874ca57eb0416de = []byte{
	// 85 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0x2d, 0x4e, 0x57, 0xb2, 0xe4, 0x62, 0x75,
	0x0e, 0x2d, 0x4e, 0x2d, 0x12, 0x12, 0xe1, 0x62, 0x4d, 0xcd, 0x4d, 0xcc, 0xcc, 0x91, 0x60, 0x54,
	0x60, 0xd2, 0xe0, 0x0c, 0x82, 0x70, 0x84, 0xa4, 0xb8, 0x38, 0x0a, 0x12, 0x8b, 0x8b, 0xcb, 0xf3,
	0x8b, 0x52, 0x24, 0x98, 0xc0, 0x12, 0x70, 0x3e, 0x20, 0x00, 0x00, 0xff, 0xff, 0x48, 0xda, 0xbe,
	0x78, 0x4c, 0x00, 0x00, 0x00,
}
