//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_ThreadPriorityWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.ThreadPriority));
		L.RegVar("Low", get_Low, null);
		L.RegVar("BelowNormal", get_BelowNormal, null);
		L.RegVar("Normal", get_Normal, null);
		L.RegVar("High", get_High, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<UnityEngine.ThreadPriority>.Check = CheckType;
		StackTraits<UnityEngine.ThreadPriority>.Push = Push;
	}

	static void Push(IntPtr L, UnityEngine.ThreadPriority arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(UnityEngine.ThreadPriority), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Low(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.ThreadPriority.Low);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BelowNormal(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.ThreadPriority.BelowNormal);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Normal(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.ThreadPriority.Normal);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_High(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.ThreadPriority.High);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UnityEngine.ThreadPriority o = (UnityEngine.ThreadPriority)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

