// Code generated by protoc-gen-go. DO NOT EDIT.
// source: MoveDTO.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PlayerDTO struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerDTO) Reset()         { *m = PlayerDTO{} }
func (m *PlayerDTO) String() string { return proto.CompactTextString(m) }
func (*PlayerDTO) ProtoMessage()    {}
func (*PlayerDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7b3ac62fbb2e1db, []int{0}
}

func (m *PlayerDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerDTO.Unmarshal(m, b)
}
func (m *PlayerDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerDTO.Marshal(b, m, deterministic)
}
func (m *PlayerDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerDTO.Merge(m, src)
}
func (m *PlayerDTO) XXX_Size() int {
	return xxx_messageInfo_PlayerDTO.Size(m)
}
func (m *PlayerDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerDTO.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerDTO proto.InternalMessageInfo

func (m *PlayerDTO) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PlayerDTO) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type MoveDTO struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Point                *Vector3 `protobuf:"bytes,2,opt,name=point,proto3" json:"point,omitempty"`
	Status               *Vector2 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveDTO) Reset()         { *m = MoveDTO{} }
func (m *MoveDTO) String() string { return proto.CompactTextString(m) }
func (*MoveDTO) ProtoMessage()    {}
func (*MoveDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7b3ac62fbb2e1db, []int{1}
}

func (m *MoveDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveDTO.Unmarshal(m, b)
}
func (m *MoveDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveDTO.Marshal(b, m, deterministic)
}
func (m *MoveDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveDTO.Merge(m, src)
}
func (m *MoveDTO) XXX_Size() int {
	return xxx_messageInfo_MoveDTO.Size(m)
}
func (m *MoveDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveDTO.DiscardUnknown(m)
}

var xxx_messageInfo_MoveDTO proto.InternalMessageInfo

func (m *MoveDTO) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MoveDTO) GetPoint() *Vector3 {
	if m != nil {
		return m.Point
	}
	return nil
}

func (m *MoveDTO) GetStatus() *Vector2 {
	if m != nil {
		return m.Status
	}
	return nil
}

type Vector3 struct {
	X                    string   `protobuf:"bytes,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    string   `protobuf:"bytes,2,opt,name=y,proto3" json:"y,omitempty"`
	Z                    string   `protobuf:"bytes,3,opt,name=z,proto3" json:"z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vector3) Reset()         { *m = Vector3{} }
func (m *Vector3) String() string { return proto.CompactTextString(m) }
func (*Vector3) ProtoMessage()    {}
func (*Vector3) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7b3ac62fbb2e1db, []int{2}
}

func (m *Vector3) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vector3.Unmarshal(m, b)
}
func (m *Vector3) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vector3.Marshal(b, m, deterministic)
}
func (m *Vector3) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vector3.Merge(m, src)
}
func (m *Vector3) XXX_Size() int {
	return xxx_messageInfo_Vector3.Size(m)
}
func (m *Vector3) XXX_DiscardUnknown() {
	xxx_messageInfo_Vector3.DiscardUnknown(m)
}

var xxx_messageInfo_Vector3 proto.InternalMessageInfo

func (m *Vector3) GetX() string {
	if m != nil {
		return m.X
	}
	return ""
}

func (m *Vector3) GetY() string {
	if m != nil {
		return m.Y
	}
	return ""
}

func (m *Vector3) GetZ() string {
	if m != nil {
		return m.Z
	}
	return ""
}

type Vector2 struct {
	X                    string   `protobuf:"bytes,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    string   `protobuf:"bytes,2,opt,name=y,proto3" json:"y,omitempty"`
	Runable              bool     `protobuf:"varint,3,opt,name=runable,proto3" json:"runable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vector2) Reset()         { *m = Vector2{} }
func (m *Vector2) String() string { return proto.CompactTextString(m) }
func (*Vector2) ProtoMessage()    {}
func (*Vector2) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7b3ac62fbb2e1db, []int{3}
}

func (m *Vector2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vector2.Unmarshal(m, b)
}
func (m *Vector2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vector2.Marshal(b, m, deterministic)
}
func (m *Vector2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vector2.Merge(m, src)
}
func (m *Vector2) XXX_Size() int {
	return xxx_messageInfo_Vector2.Size(m)
}
func (m *Vector2) XXX_DiscardUnknown() {
	xxx_messageInfo_Vector2.DiscardUnknown(m)
}

var xxx_messageInfo_Vector2 proto.InternalMessageInfo

func (m *Vector2) GetX() string {
	if m != nil {
		return m.X
	}
	return ""
}

func (m *Vector2) GetY() string {
	if m != nil {
		return m.Y
	}
	return ""
}

func (m *Vector2) GetRunable() bool {
	if m != nil {
		return m.Runable
	}
	return false
}

func init() {
	proto.RegisterType((*PlayerDTO)(nil), "msg.PlayerDTO")
	proto.RegisterType((*MoveDTO)(nil), "msg.MoveDTO")
	proto.RegisterType((*Vector3)(nil), "msg.Vector3")
	proto.RegisterType((*Vector2)(nil), "msg.Vector2")
}

func init() { proto.RegisterFile("MoveDTO.proto", fileDescriptor_e7b3ac62fbb2e1db) }

var fileDescriptor_e7b3ac62fbb2e1db = []byte{
	// 209 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xf5, 0xcd, 0x2f, 0x4b,
	0x75, 0x09, 0xf1, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0x2d, 0x4e, 0x57, 0x32,
	0xe7, 0xe2, 0x0c, 0xc8, 0x49, 0xac, 0x4c, 0x2d, 0x72, 0x09, 0xf1, 0x17, 0xe2, 0xe3, 0x62, 0xca,
	0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x62, 0xca, 0x4c, 0x11, 0x92, 0xe2, 0xe2, 0x08,
	0x2d, 0x4e, 0x2d, 0xf2, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0xf3,
	0x95, 0x92, 0xb9, 0xd8, 0xa1, 0xc6, 0x61, 0x68, 0x53, 0xe2, 0x62, 0x2d, 0xc8, 0xcf, 0xcc, 0x2b,
	0x01, 0xeb, 0xe1, 0x36, 0xe2, 0xd1, 0xcb, 0x2d, 0x4e, 0xd7, 0x0b, 0x4b, 0x4d, 0x2e, 0xc9, 0x2f,
	0x32, 0x0e, 0x82, 0x48, 0x09, 0xa9, 0x70, 0xb1, 0x15, 0x97, 0x24, 0x96, 0x94, 0x16, 0x4b, 0x30,
	0x63, 0x28, 0x32, 0x0a, 0x82, 0xca, 0x29, 0x19, 0x73, 0xb1, 0x43, 0xf5, 0x09, 0xf1, 0x70, 0x31,
	0x56, 0x80, 0xed, 0xe0, 0x0c, 0x62, 0xac, 0x00, 0xf1, 0x2a, 0xa1, 0x4e, 0x62, 0xac, 0x04, 0xf1,
	0xaa, 0xc0, 0xe6, 0x70, 0x06, 0x31, 0x56, 0x29, 0xd9, 0xc3, 0x34, 0x19, 0xe1, 0xd5, 0x24, 0xc1,
	0xc5, 0x5e, 0x54, 0x9a, 0x97, 0x98, 0x94, 0x93, 0x0a, 0xd6, 0xca, 0x11, 0x04, 0xe3, 0x26, 0xb1,
	0x81, 0xc3, 0xc7, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x08, 0xb1, 0x81, 0x6a, 0x30, 0x01, 0x00,
	0x00,
}
