// Code generated by protoc-gen-go. DO NOT EDIT.
// source: person.proto

package person

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Phone_PHONE_TYPE int32

const (
	Phone_MOBILE Phone_PHONE_TYPE = 1
	Phone_HOME   Phone_PHONE_TYPE = 2
)

var Phone_PHONE_TYPE_name = map[int32]string{
	1: "MOBILE",
	2: "HOME",
}

var Phone_PHONE_TYPE_value = map[string]int32{
	"MOBILE": 1,
	"HOME":   2,
}

func (x Phone_PHONE_TYPE) Enum() *Phone_PHONE_TYPE {
	p := new(Phone_PHONE_TYPE)
	*p = x
	return p
}

func (x Phone_PHONE_TYPE) String() string {
	return proto.EnumName(Phone_PHONE_TYPE_name, int32(x))
}

func (x *Phone_PHONE_TYPE) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Phone_PHONE_TYPE_value, data, "Phone_PHONE_TYPE")
	if err != nil {
		return err
	}
	*x = Phone_PHONE_TYPE(value)
	return nil
}

func (Phone_PHONE_TYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{1, 0}
}

type Person struct {
	Id                           *int32   `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Name                         *string  `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Email                        *string  `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral         struct{} `json:"-"`
	proto.XXX_InternalExtensions `json:"-"`
	XXX_unrecognized             []byte `json:"-"`
	XXX_sizecache                int32  `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{0}
}

var extRange_Person = []proto.ExtensionRange{
	{Start: 10, End: 536870911},
}

func (*Person) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_Person
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Person) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Person) GetEmail() string {
	if m != nil && m.Email != nil {
		return *m.Email
	}
	return ""
}

type Phone struct {
	Num                  *string           `protobuf:"bytes,1,opt,name=num" json:"num,omitempty"`
	Type                 *Phone_PHONE_TYPE `protobuf:"varint,2,opt,name=type,enum=Phone_PHONE_TYPE" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Phone) Reset()         { *m = Phone{} }
func (m *Phone) String() string { return proto.CompactTextString(m) }
func (*Phone) ProtoMessage()    {}
func (*Phone) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{1}
}

func (m *Phone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Phone.Unmarshal(m, b)
}
func (m *Phone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Phone.Marshal(b, m, deterministic)
}
func (m *Phone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Phone.Merge(m, src)
}
func (m *Phone) XXX_Size() int {
	return xxx_messageInfo_Phone.Size(m)
}
func (m *Phone) XXX_DiscardUnknown() {
	xxx_messageInfo_Phone.DiscardUnknown(m)
}

var xxx_messageInfo_Phone proto.InternalMessageInfo

func (m *Phone) GetNum() string {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return ""
}

func (m *Phone) GetType() Phone_PHONE_TYPE {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Phone_MOBILE
}

var E_Phone_Phones = &proto.ExtensionDesc{
	ExtendedType:  (*Person)(nil),
	ExtensionType: ([]*Phone)(nil),
	Field:         10,
	Name:          "Phone.phones",
	Tag:           "bytes,10,rep,name=phones",
	Filename:      "person.proto",
}

func init() {
	proto.RegisterEnum("Phone_PHONE_TYPE", Phone_PHONE_TYPE_name, Phone_PHONE_TYPE_value)
	proto.RegisterType((*Person)(nil), "Person")
	proto.RegisterExtension(E_Phone_Phones)
	proto.RegisterType((*Phone)(nil), "Phone")
}

func init() { proto.RegisterFile("person.proto", fileDescriptor_4c9e10cf24b1156d) }

var fileDescriptor_4c9e10cf24b1156d = []byte{
	// 213 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x48, 0x2d, 0x2a,
	0xce, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xf2, 0xe1, 0x62, 0x0b, 0x00, 0xf3, 0x85,
	0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18, 0x15, 0x98, 0x34, 0x58, 0x83, 0x98, 0x32, 0x53, 0x84,
	0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x98, 0x14, 0x98, 0x34, 0x38, 0x83, 0xc0, 0x6c,
	0x21, 0x11, 0x2e, 0xd6, 0xd4, 0xdc, 0xc4, 0xcc, 0x1c, 0x09, 0x66, 0x05, 0x46, 0x0d, 0xce, 0x20,
	0x08, 0x47, 0x8b, 0x83, 0x83, 0x4b, 0xa0, 0xa1, 0xa1, 0xa1, 0x81, 0x49, 0xa9, 0x97, 0x91, 0x8b,
	0x35, 0x20, 0x23, 0x3f, 0x2f, 0x55, 0x48, 0x80, 0x8b, 0x39, 0xaf, 0x34, 0x57, 0x82, 0x11, 0xac,
	0x0e, 0xc4, 0x14, 0x52, 0xe5, 0x62, 0x29, 0xa9, 0x2c, 0x00, 0x99, 0xc7, 0xa8, 0xc1, 0x67, 0x24,
	0xa8, 0x07, 0x56, 0xa7, 0x17, 0xe0, 0xe1, 0xef, 0xe7, 0x1a, 0x1f, 0x12, 0x19, 0xe0, 0x1a, 0x04,
	0x96, 0x56, 0x52, 0xe2, 0xe2, 0x42, 0x88, 0x09, 0x71, 0x71, 0xb1, 0xf9, 0xfa, 0x3b, 0x79, 0xfa,
	0xb8, 0x0a, 0x30, 0x0a, 0x71, 0x70, 0xb1, 0x78, 0xf8, 0xfb, 0xba, 0x0a, 0x30, 0x19, 0xa9, 0x73,
	0xb1, 0x15, 0x80, 0x74, 0x17, 0x0b, 0xb1, 0xeb, 0x41, 0x5c, 0x2f, 0xc1, 0xa5, 0xc0, 0xac, 0xc1,
	0x6d, 0xc4, 0x06, 0x31, 0x35, 0x08, 0x2a, 0x0d, 0x08, 0x00, 0x00, 0xff, 0xff, 0x44, 0x6d, 0xb3,
	0xee, 0xec, 0x00, 0x00, 0x00,
}
